### ISSUE TITLE
link in the members list

### ISSUE THREAD

**Issue by bruce7075** [PareshRadadiya/Mutual-Buddies#3]
Hi,

When I click the link, such as '2 mutual friends' in the member list, it goes to the same page, member list. I support this shall direct the page to mutual friends of that user I click.

**Comment by PareshRadadiya** [comment]
It should open the mutual friends popup. Didn't it?

**Comment by bruce7075** [comment]
No, it doesn't have a popup when I click it.

**Comment by PareshRadadiya** [comment]
Could you please give me an url? so I can take look into it

**Comment by bruce7075** [comment]
Sure. ichibichi.com.tw

**Comment by PareshRadadiya** [comment]
Hi @bruce7075 

Mutual friends popup is opening but members are not appearing inside dialog due to some css conflict with [animate.css](https://daneden.github.io/animate.css/) 

Please add this css for quick fix

```
 .bmf-white-popup .kleo-transform .animated.animate-when-visible, .kleo-transform .animated.animate-when-almost-visible, .cul {
    opacity: 1;
}
```

**Comment by bruce7075** [comment]
I see. Please kindly advise which file I shall add the code. Thanks very much!

**Comment by PareshRadadiya** [comment]
Yep sure, Here

> wp-content/themes/kleo/assets/css/app.min.css

Don't forget to update a theme version or You can clear cache, It would serve fresh updated css

**Comment by bruce7075** [comment]
Would any future update of Kleo theme affect this file?

**Comment by PareshRadadiya** [comment]
Oh Yeah. how could i missed it. Add it here

> wp-content/themes/kleo-child/style.css

This won't affected by any update to the parent theme

**Comment by bruce7075** [comment]
Oops! It is still not working ...

**Comment by PareshRadadiya** [comment]
Working for me see. Perhaps it is your browser cache

![screenshot from 2015-08-12 13 13 07](https://cloud.githubusercontent.com/assets/6149344/9218871/f408246e-40f3-11e5-928c-5e298eedadb1.png)

**Comment by bruce7075** [comment]
Strange! I have cleared browser cache, restart computer, reboot server but, at my side, it's still the same, no popup window, just reload the same page ...

**Comment by bruce7075** [comment]
I also test by using different computer and it's the same result.

**Comment by PareshRadadiya** [comment]
Hi @bruce7075 

That's bizarre. Probably you must wait until page has been loaded fully.  Would it be possible for me to get  screencast?

Anyway I've added link for mutual friends so It won't break in case of js error or slow net connectivity. It is not yet release but Will  release it ASAP.

**Comment by PareshRadadiya** [comment]
Hello @bruce7075

I've fixed this issue. Please update the plugin and see
