### ISSUE TITLE
Changing the template file

### ISSUE THREAD

**Issue by dcsenterprise** [PareshRadadiya/Mutual-Buddies#7]
Hello,
When clicking the Mutual Friends link on the Members page, The popup is displayed using the members-loop.php. However I have things that show using bp_directory_members_actions that I don't want to show on the popup.

I duplicated the members-loop.php file and commented out the actions I don't want to show in the popup. I named it mutual-loop.php and placed it in the buddypress/members directory. In the plugin folder I changed mutual-friends-loop.php to reflect the members/mutual-loop

It doesn't work. Even when I delete the mutual-friennds-loop.php the popup still calls the members-loop.php.

I am using a child theme with a buddypress folder to handle edits. Can you please guide me in having the popup not display these action items?

Thank you.

**Comment by PareshRadadiya** [comment]
Hello @dcsenterprise 

Mutual-Buddies has added a templating system from v1.7 onward. This means that every element displayed on a Mutual-Buddies page can be overridden.

All templates are located in a **mutual-buddies/templates** folder.To override Mutual-Buddies template files in your theme (or better yet, child theme) simply make a folder named **bmf_templates** within your theme directory, and then create the folders/template file you wish to override within it. e,x `bmf_templates/friends-loop-popup.php`
- The **friends-loop-popup.php** file output a list of mutual fiends and friends that are registered on your site in popup.
- The **friends-loop.php** file output a list of mutual fiends and friends that are registered on your site on Mutual Friends page.

Please note that we strongly recommend using a child theme in order not to lose any modifications during your theme update.
