### ISSUE TITLE
Mutual Friends tab for logged-out users

### ISSUE THREAD

**Issue by AiratTop** [PareshRadadiya/Mutual-Buddies#9]
Can you hide “Mutual Friends” tab for logged-out users from user profile?
Thanks!

https://wordpress.org/support/topic/mutual-friends-tab-for-logged-out-users/

**Comment by PareshRadadiya** [comment]
Fixed [here](https://github.com/PareshRadadiya/Mutual-Buddies/commit/60293dcde8e3e667fceb7cda8c8a698ce7f79083)

**Comment by AiratTop** [comment]
Thanks!
